/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#include "custom.h"
#include "grway/mem/err.h"
#include "grway/screen/scr.h"
#include "grway/compose/cpo_curerr_list.h"
#include "grway/compose/cpo_hiserr_list.h"
#include "grway/compose/cpo_icon_menu.h"
#include "grway/compose/cpo_item_list.h"
#include "grway/compose/cpo_keyboard_n.h"

#define SCREEN_B_CUSTOM
void screen_b_menu_custom_clicked(void)
{
    scr_open(screen_2_menu_create);
}

void screen_b_error_custom_clicked(void)
{
    scr_open(screen_6_curerr_create);
}

void screen_b_main_custom_clicked(void)
{
    scr_open(screen_1_main_create);
}

void screen_b_return_custom_clicked(void)
{
    scr_return();
}

/**
 * @brief 
 * 
 */
#define SCREEN_0_FULLDISP_CUSTOM
void screen_0_fulldisp_custom_loaded(void)
{
    scr_open(screen_1_main_create);
}

/**
 * @brief 
 * 
 */
#define SCREEN_1_MAIN_CUSTOM
void screen_1_main_refresh(lv_timer_t *timer)
{
    screen_1_main_t *scr = &ui_manager.screen_1_main;

    lv_label_set_text_fmt(scr->l_indoor_temp, "in:%d", rw_mem_param[0]);
}

void screen_1_main_custom_loaded(void)
{
    scr_refresh_timer_set_cb(screen_1_main_refresh);
}

void screen_1_main_custom_unload_start(void)
{
    
}

/**
 * @brief 
 * 
 */
#define SCREEN_2_MENU_CUSTOM
void screen_2_menu_m_cric_1_custom_clicked(void)
{
    scr_open(screen_3_status_create);
}

void screen_2_menu_m_cric_2_custom_clicked(void)
{
    scr_open(screen_4_param_create);
}

void cric_1_custom_clicked(lv_event_t * e)
{
    scr_open(screen_4_param_create);
}
cpo_icon_menu_desc_t icon_menu[] = {
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路1.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路2.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路1.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路2.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路1.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路2.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路1.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路2.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路1.png), 0},
    {cric_1_custom_clicked, LVGL_IMAGE_PATH(menu/回路2.png), 0},
    {NULL, NULL, 0},
};
void screen_2_menu_custom_loaded(void)
{
    screen_2_menu_t *scr = screen_2_menu_get(&ui_manager);

    if (scr->tv_menu) {
        lv_obj_del(scr->tv_menu);
        scr->tv_menu = cpo_icon_menu_create(scr->obj, icon_menu);
    }
}

#define SCREEN_4_PARAM_CUSTOM
cpo_item_list_desc_t param_list[] = {
    DECLARE_PARAM(param_tab_user, 0, 0),
};
void screen_4_param_custom_loaded(void)
{
    screen_4_param_t *scr = screen_4_param_get(&ui_manager);

    lv_obj_del(scr->c_param);
    scr->c_param = cpo_item_list_create(scr->obj, &param_list[0], 0);
}

void screen_4_param_custom_unload_start(void)
{
    // cpo_item_list_destroy();
}


#define SCREEN_5_KEYBOARD_N_CUSTOM
void screen_5_keyboard_n_custom_loaded(void)
{
    screen_5_keyboard_n_t *scr = screen_5_keyboard_n_get(&ui_manager);

    lv_obj_del(scr->c_keyboard_n);
    scr->c_keyboard_n = cpo_keyboard_n_create(scr->obj, 0, NULL, NULL);
}

#define SCREEN_6_CURERR_CUSTOM
void screen_6_curerr_custom_loaded(void)
{
    screen_6_curerr_t *scr = screen_6_curerr_get(&ui_manager);

    lv_obj_del(scr->c_curerr_list);
    scr->c_curerr_list = cpo_curerr_list_create(scr->obj);
}

void screen_6_curerr_b_to_hiserr_custom_clicked(void) {
    scr_open(screen_7_hiserr_create);
}

void screen_6_curerr_button_1_custom_clicked(void) {
    err_set(0, 201);
    err_deal();
}

#define SCREEN_7_HISERR_CUSTOM
void screen_7_hiserr_custom_loaded(void)
{
    screen_7_hiserr_t *scr = screen_7_hiserr_get(&ui_manager);

    lv_obj_del(scr->c_hiserr_list);
    scr->c_hiserr_list = cpo_hiserr_list_create(scr->obj);
}

void screen_7_hiserr_b_to_curerr_custom_clicked(void) {
    scr_return();
}

void custom_timer(lv_timer_t * timer)
{
    lv_mem_monitor_t mon;
    lv_mem_monitor(&mon);

    printf("LVGL memory usage:\n");
    printf("  Max used:   %6d bytes (peak)\n", mon.max_used);
    printf("  Used blocks: %d\n", mon.used_cnt);
}

// #include "board.h"
void custom_init()
{
    // if (board_init() != 0) {
    //     return;
    // }
    /* Add your codes here */
    param_data_init();
    err_init();

    lv_timer_create(custom_timer, 1000, NULL);
}

