/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "aic_lang.h"
#include "custom/custom.h"

static lang_type_t current_lang = AIC_LANG_EN;

const aic_language_t languages[] = {
    {"en", MONTSERRATMEDIUM_TTF, false},
    {"zh", DROIDSANSFALLBACK_TTF, false}
};

const char *font_names[] = {
    "montserratMedium.ttf",
    "DroidSansFallback.ttf"
};

const char *translations[2][2] = {
    {"Hello", "你好"},
    {"", ""}
};

void aic_set_language(lang_type_t lang)
{
    current_lang  = lang;
}

const char *aic_get_translation(key_id_t key)
{
    return translations[key][current_lang];
}

const lv_font_t *aic_init_lang_font(int font_id, int font_size)
{
    const lv_font_t *font = aic_font_list_find(font_id, font_size);
    if (font)
        return font;

    char font_path[256] = {0};
    snprintf(font_path, sizeof(font_path) - 1, "%s/font/%s", LVGL_STORAGE_PATH, font_names[font_id]);

    font = ui_font_init(font_path, font_size);
    if (!font) {
        LV_LOG_ERROR("Failed to init font");
        return NULL;
    }

    aic_font_list_add(font_id, font_size, font);
    return font;
}

const lv_font_t *aic_get_lang_font(int font_id, int font_size, bool c_flag)
{
    if (c_flag)
        return aic_get_c_font(font_id, font_size);
    else
        return aic_init_lang_font(font_id, font_size);
}

const lv_font_t *aic_get_multi_lang_font(int font_size)
{
    const aic_language_t *lang = get_current_lang();
    return aic_get_lang_font(lang->font_id, font_size, lang->c_flag);
}

const lv_font_t *aic_get_c_font(int font_id, int font_size)
{
    switch (font_id) {

        default:
            return NULL;
    }
}

const aic_language_t *get_current_lang()
{
    return &languages[current_lang];
}
