/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#ifndef AIC_LANG_H
#define AIC_LANG_H
#include "lvgl.h"
#include "font_list.h"

typedef enum {
    AIC_LANG_EN,
    AIC_LANG_ZH
} lang_type_t;

typedef struct {
    char *lan_name;
    int font_id;
    bool c_flag;
} aic_language_t;

typedef enum {
    SAMPLE,
    he
} key_id_t;

#define MONTSERRATMEDIUM_TTF 0
#define DROIDSANSFALLBACK_TTF 1

void aic_set_language(lang_type_t lang);

const char *aic_get_translation(key_id_t key);

const lv_font_t *aic_init_lang_font(int font_id, int font_size);

const lv_font_t *aic_get_lang_font(int font_id, int font_size, bool c_flag);

const lv_font_t *aic_get_multi_lang_font(int font_size);

const lv_font_t *aic_get_c_font(int font_id, int font_size);

const aic_language_t *get_current_lang();

#endif // AIC_LANG_H
