/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"


void screen_8_hiserr_detail_create(ui_manager_t *ui)
{
    screen_8_hiserr_detail_t *scr = screen_8_hiserr_detail_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_8_hiserr_detail_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s60_故障详情.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->c_hiserr_detail
    scr->c_hiserr_detail = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->c_hiserr_detail, 112, 60);
    lv_obj_set_size(scr->c_hiserr_detail, 800, 480);
    lv_obj_set_scrollbar_mode(scr->c_hiserr_detail, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->c_hiserr_detail
    lv_obj_set_style_bg_color(scr->c_hiserr_detail, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->c_hiserr_detail, LVGL_IMAGE_PATH(screen/s60_故障详情.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_hiserr_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->l_err_no
    scr->l_err_no = lv_label_create(scr->c_hiserr_detail);
    lv_label_set_text(scr->l_err_no, "Label");
    lv_label_set_long_mode(scr->l_err_no, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_err_no, 51, 62);
    lv_obj_set_size(scr->l_err_no, 100, 32);

    // Set style of scr->l_err_no
    lv_obj_set_style_text_font(scr->l_err_no, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_err_no, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->b_close
    scr->b_close = lv_btn_create(scr->c_hiserr_detail);
    lv_obj_t *b_close_label = lv_label_create(scr->b_close);
    lv_label_set_text(b_close_label, aic_get_translation(he));
    lv_obj_align(b_close_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_close, 731, 0);
    lv_obj_set_size(scr->b_close, 69, 56);

    // Set style of scr->b_close
    lv_obj_set_style_bg_opa(scr->b_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_close, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}

void screen_8_hiserr_detail_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_8_hiserr_detail_update_current_language();
}

void screen_8_hiserr_detail_update_current_language()
{
    screen_8_hiserr_detail_t *scr = screen_8_hiserr_detail_get(&ui_manager);
    lv_obj_set_style_text_font(scr->l_err_no, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_err_no, "Label");

    lv_obj_set_style_text_font(scr->b_close, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_close, 0), aic_get_translation(he));

}

