/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_0_fulldisp_custom_loaded(void) {
}

static void screen_0_fulldisp_loaded (lv_event_t *e) {
    screen_0_fulldisp_custom_loaded();
}


void screen_0_fulldisp_create(ui_manager_t *ui)
{
    screen_0_fulldisp_t *scr = screen_0_fulldisp_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_0_fulldisp_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s00_全显.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_0_fulldisp_loaded, LV_EVENT_SCREEN_LOADED, NULL);


}

void screen_0_fulldisp_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_0_fulldisp_update_current_language();
}

void screen_0_fulldisp_update_current_language()
{
    screen_0_fulldisp_t *scr = screen_0_fulldisp_get(&ui_manager);
}

