/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_7_hiserr_custom_loaded(void) {
}

static void screen_7_hiserr_loaded (lv_event_t *e) {
    screen_7_hiserr_custom_loaded();
}

void __attribute__((weak)) screen_b_return_custom_clicked(void) {
}

static void screen_7_hiserr_b_return_clicked (lv_event_t *e) {
    screen_b_return_custom_clicked();
}

void __attribute__((weak)) screen_7_hiserr_b_to_curerr_custom_clicked(void) {
}

static void screen_7_hiserr_b_to_curerr_clicked (lv_event_t *e) {
    screen_7_hiserr_b_to_curerr_custom_clicked();
}


void screen_7_hiserr_create(ui_manager_t *ui)
{
    screen_7_hiserr_t *scr = screen_7_hiserr_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_7_hiserr_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s18_历史故障记录.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_7_hiserr_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->c_hiserr_list
    scr->c_hiserr_list = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->c_hiserr_list, 179, 203);
    lv_obj_set_size(scr->c_hiserr_list, 663, 270);
    lv_obj_set_scrollbar_mode(scr->c_hiserr_list, LV_SCROLLBAR_MODE_ACTIVE);

    // Set style of scr->c_hiserr_list
    lv_obj_set_style_bg_color(scr->c_hiserr_list, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_hiserr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->c_hiserr_item
    scr->c_hiserr_item = lv_obj_create(scr->c_hiserr_list);
    lv_obj_set_pos(scr->c_hiserr_item, 9, 7);
    lv_obj_set_size(scr->c_hiserr_item, 637, 44);
    lv_obj_set_scrollbar_mode(scr->c_hiserr_item, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->c_hiserr_item
    lv_obj_set_style_bg_color(scr->c_hiserr_item, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_hiserr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->l_time
    scr->l_time = lv_label_create(scr->c_hiserr_item);
    lv_label_set_text(scr->l_time, "Label");
    lv_label_set_long_mode(scr->l_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_time, 27, 9);
    lv_obj_set_size(scr->l_time, 229, 26);

    // Set style of scr->l_time
    lv_obj_set_style_text_font(scr->l_time, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->b_detail
    scr->b_detail = lv_btn_create(scr->c_hiserr_item);
    lv_obj_t *b_detail_label = lv_label_create(scr->b_detail);
    lv_label_set_text(b_detail_label, "Button");
    lv_obj_align(b_detail_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_detail, 455, 1);
    lv_obj_set_size(scr->b_detail, 87, 43);

    // Set style of scr->b_detail
    lv_obj_set_style_text_font(scr->b_detail, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->b_return
    scr->b_return = lv_btn_create(scr->obj);
    lv_obj_t *b_return_label = lv_label_create(scr->b_return);
    lv_label_set_text(b_return_label, aic_get_translation(he));
    lv_obj_align(b_return_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_return, 125, 72);
    lv_obj_set_size(scr->b_return, 80, 80);

    // Set style of scr->b_return
    lv_obj_set_style_bg_opa(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_return
    lv_obj_add_event_cb(scr->b_return, screen_7_hiserr_b_return_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_to_curerr
    scr->b_to_curerr = lv_btn_create(scr->obj);
    lv_obj_t *b_to_curerr_label = lv_label_create(scr->b_to_curerr);
    lv_label_set_text(b_to_curerr_label, "Button");
    lv_obj_align(b_to_curerr_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_to_curerr, 187, 102);
    lv_obj_set_size(scr->b_to_curerr, 325, 44);

    // Set style of scr->b_to_curerr
    lv_obj_set_style_text_font(scr->b_to_curerr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_to_curerr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_to_curerr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_to_curerr
    lv_obj_add_event_cb(scr->b_to_curerr, screen_7_hiserr_b_to_curerr_clicked, LV_EVENT_CLICKED, NULL);


}

void screen_7_hiserr_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_7_hiserr_update_current_language();
}

void screen_7_hiserr_update_current_language()
{
    screen_7_hiserr_t *scr = screen_7_hiserr_get(&ui_manager);
    lv_obj_set_style_text_font(scr->l_time, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_time, "Label");

    lv_obj_set_style_text_font(scr->b_detail, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_detail, 0), "Button");

    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_return, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_to_curerr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_to_curerr, 0), "Button");

}

