/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_6_curerr_custom_loaded(void) {
}

static void screen_6_curerr_loaded (lv_event_t *e) {
    screen_6_curerr_custom_loaded();
}

void __attribute__((weak)) screen_6_curerr_button_1_custom_clicked(void) {
}

static void screen_6_curerr_button_1_clicked (lv_event_t *e) {
    screen_6_curerr_button_1_custom_clicked();
}

void __attribute__((weak)) screen_b_return_custom_clicked(void) {
}

static void screen_6_curerr_b_return_clicked (lv_event_t *e) {
    screen_b_return_custom_clicked();
}

void __attribute__((weak)) screen_6_curerr_b_to_hiserr_custom_clicked(void) {
}

static void screen_6_curerr_b_to_hiserr_clicked (lv_event_t *e) {
    screen_6_curerr_b_to_hiserr_custom_clicked();
}


void screen_6_curerr_create(ui_manager_t *ui)
{
    screen_6_curerr_t *scr = screen_6_curerr_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_6_curerr_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s17_当前故障记录.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_6_curerr_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->c_curerr_list
    scr->c_curerr_list = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->c_curerr_list, 179, 203);
    lv_obj_set_size(scr->c_curerr_list, 663, 270);
    lv_obj_set_scrollbar_mode(scr->c_curerr_list, LV_SCROLLBAR_MODE_AUTO);

    // Set style of scr->c_curerr_list
    lv_obj_set_style_bg_color(scr->c_curerr_list, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_curerr_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->c_curerr_item
    scr->c_curerr_item = lv_obj_create(scr->c_curerr_list);
    lv_obj_set_pos(scr->c_curerr_item, 9, 7);
    lv_obj_set_size(scr->c_curerr_item, 637, 44);
    lv_obj_set_scrollbar_mode(scr->c_curerr_item, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->c_curerr_item
    lv_obj_set_style_bg_color(scr->c_curerr_item, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_curerr_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->l_curno
    scr->l_curno = lv_label_create(scr->c_curerr_item);
    lv_label_set_text(scr->l_curno, "Label");
    lv_label_set_long_mode(scr->l_curno, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_curno, 27, 9);
    lv_obj_set_size(scr->l_curno, 229, 26);

    // Set style of scr->l_curno
    lv_obj_set_style_text_font(scr->l_curno, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_curno, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->l_curerr
    scr->l_curerr = lv_label_create(scr->c_curerr_item);
    lv_label_set_text(scr->l_curerr, "Label");
    lv_label_set_long_mode(scr->l_curerr, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_curerr, 279, 7);
    lv_obj_set_size(scr->l_curerr, 341, 30);

    // Set style of scr->l_curerr
    lv_obj_set_style_text_font(scr->l_curerr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_curerr, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Button");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 463, 486);
    lv_obj_set_size(scr->button_1, 87, 43);

    // Set style of scr->button_1
    lv_obj_set_style_text_font(scr->button_1, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, screen_6_curerr_button_1_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_return
    scr->b_return = lv_btn_create(scr->obj);
    lv_obj_t *b_return_label = lv_label_create(scr->b_return);
    lv_label_set_text(b_return_label, aic_get_translation(he));
    lv_obj_align(b_return_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_return, 125, 72);
    lv_obj_set_size(scr->b_return, 80, 80);

    // Set style of scr->b_return
    lv_obj_set_style_bg_opa(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_return
    lv_obj_add_event_cb(scr->b_return, screen_6_curerr_b_return_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_to_hiserr
    scr->b_to_hiserr = lv_btn_create(scr->obj);
    lv_obj_t *b_to_hiserr_label = lv_label_create(scr->b_to_hiserr);
    lv_label_set_text(b_to_hiserr_label, "Button");
    lv_obj_align(b_to_hiserr_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_to_hiserr, 507, 102);
    lv_obj_set_size(scr->b_to_hiserr, 325, 44);

    // Set style of scr->b_to_hiserr
    lv_obj_set_style_text_font(scr->b_to_hiserr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_to_hiserr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_to_hiserr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_to_hiserr
    lv_obj_add_event_cb(scr->b_to_hiserr, screen_6_curerr_b_to_hiserr_clicked, LV_EVENT_CLICKED, NULL);


}

void screen_6_curerr_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_6_curerr_update_current_language();
}

void screen_6_curerr_update_current_language()
{
    screen_6_curerr_t *scr = screen_6_curerr_get(&ui_manager);
    lv_obj_set_style_text_font(scr->l_curno, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_curno, "Label");

    lv_obj_set_style_text_font(scr->l_curerr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_curerr, "Label");

    lv_obj_set_style_text_font(scr->button_1, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->button_1, 0), "Button");

    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_return, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_to_hiserr, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_to_hiserr, 0), "Button");

}

