/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_2_menu_custom_loaded(void) {
}

static void screen_2_menu_loaded (lv_event_t *e) {
    screen_2_menu_custom_loaded();
}

void __attribute__((weak)) screen_2_menu_m_cric_1_custom_clicked(void) {
}

static void screen_2_menu_c_icon_clicked (lv_event_t *e) {
    screen_2_menu_m_cric_1_custom_clicked();
}

void __attribute__((weak)) screen_b_error_custom_clicked(void) {
}

static void screen_2_menu_b_error_clicked (lv_event_t *e) {
    screen_b_error_custom_clicked();
}

void __attribute__((weak)) screen_b_main_custom_clicked(void) {
}

static void screen_2_menu_b_main_clicked (lv_event_t *e) {
    screen_b_main_custom_clicked();
}

void __attribute__((weak)) screen_b_return_custom_clicked(void) {
}

static void screen_2_menu_b_return_clicked (lv_event_t *e) {
    screen_b_return_custom_clicked();
}


void screen_2_menu_create(ui_manager_t *ui)
{
    screen_2_menu_t *scr = screen_2_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_2_menu_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s10_菜单页.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_2_menu_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->tv_menu
    scr->tv_menu = lv_tileview_create(scr->obj);
    lv_obj_t *screen_2_menu_tv_menu_tile_1 = lv_tileview_add_tile(scr->tv_menu, 0, 0, LV_DIR_ALL);
    lv_obj_t *screen_2_menu_tv_menu_tile_2 = lv_tileview_add_tile(scr->tv_menu, 1, 0, LV_DIR_ALL);
    lv_obj_set_pos(scr->tv_menu, 122, 114);
    lv_obj_set_size(scr->tv_menu, 780, 323);
    lv_obj_set_scrollbar_mode(scr->tv_menu, LV_SCROLLBAR_MODE_ACTIVE);

    // Set style of scr->tv_menu
    lv_obj_set_style_bg_color(scr->tv_menu, lv_color_hex(0xc5c5c5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->tv_menu, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->tv_menu, lv_color_hex(0xc5c5c5), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Init scr->c_icon
    scr->c_icon = lv_obj_create(screen_2_menu_tv_menu_tile_1);
    lv_obj_set_pos(scr->c_icon, 75, 25);
    lv_obj_set_size(scr->c_icon, 150, 145);
    lv_obj_set_scrollbar_mode(scr->c_icon, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->c_icon
    lv_obj_set_style_bg_color(scr->c_icon, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->c_icon
    lv_obj_add_event_cb(scr->c_icon, screen_2_menu_c_icon_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->l_icon
    scr->l_icon = lv_label_create(scr->c_icon);
    lv_label_set_text(scr->l_icon, "Label");
    lv_label_set_long_mode(scr->l_icon, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_icon, 4, 103);
    lv_obj_set_size(scr->l_icon, 141, 42);

    // Set style of scr->l_icon
    lv_obj_set_style_text_font(scr->l_icon, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->l_icon, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->i_cric_1
    scr->i_cric_1 = lv_img_create(scr->c_icon);
    lv_img_set_src(scr->i_cric_1, LVGL_IMAGE_PATH(menu/回路1.png));
    lv_img_set_pivot(scr->i_cric_1, 50, 50);
    lv_img_set_angle(scr->i_cric_1, 0);
    lv_obj_set_style_img_opa(scr->i_cric_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->i_cric_1, 25, 0);

    // Init scr->animImg_1
    scr->animImg_1 = lv_animimg_create(screen_2_menu_tv_menu_tile_1);
    static const char *animImg_1_imgs[3] = {
        LVGL_IMAGE_PATH(menu/回路1.png),
        LVGL_IMAGE_PATH(menu/回路2.png),
        LVGL_IMAGE_PATH(menu/热水.png),
    };
    lv_animimg_set_src(scr->animImg_1, (const void **)animImg_1_imgs, 3);
    lv_animimg_set_duration(scr->animImg_1, 500);
    lv_animimg_set_repeat_count(scr->animImg_1, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_1);
    lv_obj_set_pos(scr->animImg_1, 682, 223);
    lv_obj_set_size(scr->animImg_1, 100, 100);

    // Init scr->b_error
    scr->b_error = lv_btn_create(scr->obj);
    lv_obj_t *b_error_label = lv_label_create(scr->b_error);
    lv_label_set_text(b_error_label, aic_get_translation(he));
    lv_obj_align(b_error_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_error, 365, 452);
    lv_obj_set_size(scr->b_error, 80, 80);

    // Set style of scr->b_error
    lv_obj_set_style_bg_opa(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_error
    lv_obj_add_event_cb(scr->b_error, screen_2_menu_b_error_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_main
    scr->b_main = lv_btn_create(scr->obj);
    lv_obj_t *b_main_label = lv_label_create(scr->b_main);
    lv_label_set_text(b_main_label, aic_get_translation(he));
    lv_obj_align(b_main_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_main, 594, 452);
    lv_obj_set_size(scr->b_main, 80, 80);

    // Set style of scr->b_main
    lv_obj_set_style_bg_opa(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_main, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_main
    lv_obj_add_event_cb(scr->b_main, screen_2_menu_b_main_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_return
    scr->b_return = lv_btn_create(scr->obj);
    lv_obj_t *b_return_label = lv_label_create(scr->b_return);
    lv_label_set_text(b_return_label, aic_get_translation(he));
    lv_obj_align(b_return_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_return, 781, 451);
    lv_obj_set_size(scr->b_return, 80, 80);

    // Set style of scr->b_return
    lv_obj_set_style_bg_opa(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_return
    lv_obj_add_event_cb(scr->b_return, screen_2_menu_b_return_clicked, LV_EVENT_CLICKED, NULL);


}

void screen_2_menu_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_2_menu_update_current_language();
}

void screen_2_menu_update_current_language()
{
    screen_2_menu_t *scr = screen_2_menu_get(&ui_manager);
    lv_obj_set_style_text_font(scr->l_icon, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_icon, "Label");

    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_error, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_main, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_main, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_return, 0), aic_get_translation(he));

}

