/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_5_keyboard_n_custom_loaded(void) {
}

static void screen_5_keyboard_n_loaded (lv_event_t *e) {
    screen_5_keyboard_n_custom_loaded();
}


void screen_5_keyboard_n_create(ui_manager_t *ui)
{
    screen_5_keyboard_n_t *scr = screen_5_keyboard_n_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_5_keyboard_n_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_5_keyboard_n_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->c_keyboard_n
    scr->c_keyboard_n = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->c_keyboard_n, 112, 344);
    lv_obj_set_size(scr->c_keyboard_n, 800, 256);
    lv_obj_set_scrollbar_mode(scr->c_keyboard_n, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->c_keyboard_n
    lv_obj_set_style_bg_color(scr->c_keyboard_n, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->c_keyboard_n, LVGL_IMAGE_PATH(widget/键盘.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->c_keyboard_n, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}

void screen_5_keyboard_n_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_5_keyboard_n_update_current_language();
}

void screen_5_keyboard_n_update_current_language()
{
    screen_5_keyboard_n_t *scr = screen_5_keyboard_n_get(&ui_manager);
}

