/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_3_status_custom_load_start(void) {
}

static void screen_3_status_load_start (lv_event_t *e) {
    screen_3_status_custom_load_start();
}

void __attribute__((weak)) screen_b_return_custom_clicked(void) {
}

static void screen_3_status_b_return_clicked (lv_event_t *e) {
    screen_b_return_custom_clicked();
}

void __attribute__((weak)) screen_b_main_custom_clicked(void) {
}

static void screen_3_status_b_main_clicked (lv_event_t *e) {
    screen_b_main_custom_clicked();
}

void __attribute__((weak)) screen_b_error_custom_clicked(void) {
}

static void screen_3_status_b_error_clicked (lv_event_t *e) {
    screen_b_error_custom_clicked();
}


void screen_3_status_create(ui_manager_t *ui)
{
    screen_3_status_t *scr = screen_3_status_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_3_status_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s10_菜单页.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_3_status_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->b_return
    scr->b_return = lv_btn_create(scr->obj);
    lv_obj_t *b_return_label = lv_label_create(scr->b_return);
    lv_label_set_text(b_return_label, aic_get_translation(he));
    lv_obj_align(b_return_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_return, 781, 451);
    lv_obj_set_size(scr->b_return, 80, 80);

    // Set style of scr->b_return
    lv_obj_set_style_bg_opa(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_return
    lv_obj_add_event_cb(scr->b_return, screen_3_status_b_return_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_main
    scr->b_main = lv_btn_create(scr->obj);
    lv_obj_t *b_main_label = lv_label_create(scr->b_main);
    lv_label_set_text(b_main_label, aic_get_translation(he));
    lv_obj_align(b_main_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_main, 594, 452);
    lv_obj_set_size(scr->b_main, 80, 80);

    // Set style of scr->b_main
    lv_obj_set_style_bg_opa(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_main, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_main
    lv_obj_add_event_cb(scr->b_main, screen_3_status_b_main_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_error
    scr->b_error = lv_btn_create(scr->obj);
    lv_obj_t *b_error_label = lv_label_create(scr->b_error);
    lv_label_set_text(b_error_label, aic_get_translation(he));
    lv_obj_align(b_error_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_error, 360, 455);
    lv_obj_set_size(scr->b_error, 80, 80);

    // Set style of scr->b_error
    lv_obj_set_style_bg_opa(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_error
    lv_obj_add_event_cb(scr->b_error, screen_3_status_b_error_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->l_title
    scr->l_title = lv_label_create(scr->obj);
    lv_label_set_text(scr->l_title, "Label");
    lv_label_set_long_mode(scr->l_title, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_title, 162, 64);
    lv_obj_set_size(scr->l_title, 700, 37);

    // Set style of scr->l_title
    lv_obj_set_style_text_font(scr->l_title, aic_get_lang_font(DROIDSANSFALLBACK_TTF, 30, get_current_lang()->c_flag), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_title, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->l_title, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}

void screen_3_status_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_3_status_update_current_language();
}

void screen_3_status_update_current_language()
{
    screen_3_status_t *scr = screen_3_status_get(&ui_manager);
    lv_obj_set_style_text_font(scr->b_return, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_return, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_main, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_main, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_error, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->l_title, aic_get_lang_font(DROIDSANSFALLBACK_TTF, 30, get_current_lang()->c_flag), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_title, "Label");

}

