/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_1_main_custom_loaded(void) {
}
void __attribute__((weak)) screen_1_main_custom_unload_start(void) {
}

static void screen_1_main_unload_start (lv_event_t *e) {
    screen_1_main_custom_unload_start();
}

static void screen_1_main_loaded (lv_event_t *e) {
    screen_1_main_custom_loaded();
}

void __attribute__((weak)) screen_b_menu_custom_clicked(void) {
}

static void screen_1_main_b_menu_clicked (lv_event_t *e) {
    screen_b_menu_custom_clicked();
}

void __attribute__((weak)) screen_b_error_custom_clicked(void) {
}

static void screen_1_main_b_error_clicked (lv_event_t *e) {
    screen_b_error_custom_clicked();
}


void screen_1_main_create(ui_manager_t *ui)
{
    screen_1_main_t *scr = screen_1_main_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_1_main_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(screen/s01_主界面.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_1_main_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, screen_1_main_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->b_menu
    scr->b_menu = lv_btn_create(scr->obj);
    lv_obj_t *b_menu_label = lv_label_create(scr->b_menu);
    lv_label_set_text(b_menu_label, aic_get_translation(he));
    lv_obj_align(b_menu_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_menu, 166, 451);
    lv_obj_set_size(scr->b_menu, 80, 80);

    // Set style of scr->b_menu
    lv_obj_set_style_bg_opa(scr->b_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_menu, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_menu
    lv_obj_add_event_cb(scr->b_menu, screen_1_main_b_menu_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_error
    scr->b_error = lv_btn_create(scr->obj);
    lv_obj_t *b_error_label = lv_label_create(scr->b_error);
    lv_label_set_text(b_error_label, aic_get_translation(he));
    lv_obj_align(b_error_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_error, 359, 451);
    lv_obj_set_size(scr->b_error, 80, 80);

    // Set style of scr->b_error
    lv_obj_set_style_bg_opa(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_error, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->b_error
    lv_obj_add_event_cb(scr->b_error, screen_1_main_b_error_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->b_mode
    scr->b_mode = lv_btn_create(scr->obj);
    lv_obj_t *b_mode_label = lv_label_create(scr->b_mode);
    lv_label_set_text(b_mode_label, aic_get_translation(he));
    lv_obj_align(b_mode_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_mode, 765, 323);
    lv_obj_set_size(scr->b_mode, 99, 99);

    // Set style of scr->b_mode
    lv_obj_set_style_bg_opa(scr->b_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->b_mode, LVGL_IMAGE_PATH(icon/m_1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_mode, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->b_onoff
    scr->b_onoff = lv_btn_create(scr->obj);
    lv_obj_t *b_onoff_label = lv_label_create(scr->b_onoff);
    lv_label_set_text(b_onoff_label, aic_get_translation(he));
    lv_obj_align(b_onoff_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->b_onoff, 765, 164);
    lv_obj_set_size(scr->b_onoff, 99, 99);

    // Set style of scr->b_onoff
    lv_obj_set_style_bg_opa(scr->b_onoff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->b_onoff, LVGL_IMAGE_PATH(icon/p_off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->b_onoff, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->b_onoff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->b_onoff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->in_door
    scr->in_door = lv_img_create(scr->obj);
    lv_img_set_src(scr->in_door, LVGL_IMAGE_PATH(icon/home.png));
    lv_img_set_pivot(scr->in_door, 50, 50);
    lv_img_set_angle(scr->in_door, 0);
    lv_obj_set_style_img_opa(scr->in_door, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->in_door, 246, 323);

    // Init scr->status_bar
    scr->status_bar = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->status_bar, 333, 65);
    lv_obj_set_size(scr->status_bar, 359, 83);
    lv_obj_set_scrollbar_mode(scr->status_bar, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->status_bar
    lv_obj_set_style_bg_color(scr->status_bar, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->status_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->s_1
    scr->s_1 = lv_img_create(scr->status_bar);
    lv_img_set_src(scr->s_1, LVGL_IMAGE_PATH(icon/s_01.png));
    lv_img_set_pivot(scr->s_1, 50, 50);
    lv_img_set_angle(scr->s_1, 0);
    lv_obj_set_style_img_opa(scr->s_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->s_1, 0, 0);

    // Init scr->l_indoor_temp
    scr->l_indoor_temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->l_indoor_temp, aic_get_translation(he));
    lv_label_set_long_mode(scr->l_indoor_temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->l_indoor_temp, 359, 335);
    lv_obj_set_size(scr->l_indoor_temp, 100, 32);

    // Set style of scr->l_indoor_temp
    lv_obj_set_style_text_font(scr->l_indoor_temp, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->l_indoor_temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->l_indoor_temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, aic_get_translation(SAMPLE));
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 490, 215);
    lv_obj_set_size(scr->label_2, 100, 32);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);


}

void screen_1_main_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_1_main_update_current_language();
}

void screen_1_main_update_current_language()
{
    screen_1_main_t *scr = screen_1_main_get(&ui_manager);
    lv_obj_set_style_text_font(scr->b_menu, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_menu, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_error, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_error, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_mode, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_mode, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->b_onoff, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(lv_obj_get_child(scr->b_onoff, 0), aic_get_translation(he));

    lv_obj_set_style_text_font(scr->l_indoor_temp, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->l_indoor_temp, aic_get_translation(he));

    lv_obj_set_style_text_font(scr->label_2, aic_get_multi_lang_font(16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->label_2, aic_get_translation(SAMPLE));

}

