/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"
#include "aic_lang.h"

typedef struct {
    lv_obj_t *obj;
} screen_0_fulldisp_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *b_menu;
    lv_obj_t *b_error;
    lv_obj_t *b_mode;
    lv_obj_t *b_onoff;
    lv_obj_t *in_door;
    lv_obj_t *status_bar;
    lv_obj_t *s_1;
    lv_obj_t *l_indoor_temp;
    lv_obj_t *label_2;
} screen_1_main_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *tv_menu;
    lv_obj_t *c_icon;
    lv_obj_t *l_icon;
    lv_obj_t *i_cric_1;
    lv_obj_t *animImg_1;
    lv_obj_t *b_error;
    lv_obj_t *b_main;
    lv_obj_t *b_return;
} screen_2_menu_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *b_return;
    lv_obj_t *b_main;
    lv_obj_t *b_error;
    lv_obj_t *l_title;
} screen_3_status_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *b_return;
    lv_obj_t *b_main;
    lv_obj_t *b_error;
    lv_obj_t *c_param;
    lv_obj_t *param_item;
    lv_obj_t *l_item;
    lv_obj_t *b_item;
    lv_obj_t *l_title;
} screen_4_param_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *c_keyboard_n;
} screen_5_keyboard_n_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *c_curerr_list;
    lv_obj_t *c_curerr_item;
    lv_obj_t *l_curno;
    lv_obj_t *l_curerr;
    lv_obj_t *button_1;
    lv_obj_t *b_return;
    lv_obj_t *b_to_hiserr;
} screen_6_curerr_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *c_hiserr_list;
    lv_obj_t *c_hiserr_item;
    lv_obj_t *l_time;
    lv_obj_t *b_detail;
    lv_obj_t *b_return;
    lv_obj_t *b_to_curerr;
} screen_7_hiserr_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *c_hiserr_detail;
    lv_obj_t *l_err_no;
    lv_obj_t *b_close;
} screen_8_hiserr_detail_t;


typedef struct {
    bool auto_del;
    screen_0_fulldisp_t screen_0_fulldisp;
    screen_1_main_t screen_1_main;
    screen_2_menu_t screen_2_menu;
    screen_3_status_t screen_3_status;
    screen_4_param_t screen_4_param;
    screen_5_keyboard_n_t screen_5_keyboard_n;
    screen_6_curerr_t screen_6_curerr;
    screen_7_hiserr_t screen_7_hiserr;
    screen_8_hiserr_detail_t screen_8_hiserr_detail;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_0_fulldisp_t *screen_0_fulldisp_get(ui_manager_t *ui)
{
    return &ui->screen_0_fulldisp;
}

static inline screen_1_main_t *screen_1_main_get(ui_manager_t *ui)
{
    return &ui->screen_1_main;
}

static inline screen_2_menu_t *screen_2_menu_get(ui_manager_t *ui)
{
    return &ui->screen_2_menu;
}

static inline screen_3_status_t *screen_3_status_get(ui_manager_t *ui)
{
    return &ui->screen_3_status;
}

static inline screen_4_param_t *screen_4_param_get(ui_manager_t *ui)
{
    return &ui->screen_4_param;
}

static inline screen_5_keyboard_n_t *screen_5_keyboard_n_get(ui_manager_t *ui)
{
    return &ui->screen_5_keyboard_n;
}

static inline screen_6_curerr_t *screen_6_curerr_get(ui_manager_t *ui)
{
    return &ui->screen_6_curerr;
}

static inline screen_7_hiserr_t *screen_7_hiserr_get(ui_manager_t *ui)
{
    return &ui->screen_7_hiserr;
}

static inline screen_8_hiserr_detail_t *screen_8_hiserr_detail_get(ui_manager_t *ui)
{
    return &ui->screen_8_hiserr_detail;
}


void screen_0_fulldisp_create(ui_manager_t *ui);
void screen_1_main_create(ui_manager_t *ui);
void screen_2_menu_create(ui_manager_t *ui);
void screen_3_status_create(ui_manager_t *ui);
void screen_4_param_create(ui_manager_t *ui);
void screen_5_keyboard_n_create(ui_manager_t *ui);
void screen_6_curerr_create(ui_manager_t *ui);
void screen_7_hiserr_create(ui_manager_t *ui);
void screen_8_hiserr_detail_create(ui_manager_t *ui);

void screen_0_fulldisp_update_language(lang_type_t lang);
void screen_0_fulldisp_update_current_language();
void screen_1_main_update_language(lang_type_t lang);
void screen_1_main_update_current_language();
void screen_2_menu_update_language(lang_type_t lang);
void screen_2_menu_update_current_language();
void screen_3_status_update_language(lang_type_t lang);
void screen_3_status_update_current_language();
void screen_4_param_update_language(lang_type_t lang);
void screen_4_param_update_current_language();
void screen_5_keyboard_n_update_language(lang_type_t lang);
void screen_5_keyboard_n_update_current_language();
void screen_6_curerr_update_language(lang_type_t lang);
void screen_6_curerr_update_current_language();
void screen_7_hiserr_update_language(lang_type_t lang);
void screen_7_hiserr_update_current_language();
void screen_8_hiserr_detail_update_language(lang_type_t lang);
void screen_8_hiserr_detail_update_current_language();



extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
